Repository fylein/fyle_integrations_imports, pull requests merged in 2025-05, with the labels that each got.

#38 feat: handle merchant, custom field disable/deletion
  modules/base.py
  modules/categories.py
  modules/cost_centers.py
  modules/expense_custom_fields.py
  modules/merchants.py
  modules/projects.py
Labels: size/M

#39 fix: inactive values sync in first run
  modules/base.py
  modules/categories.py
  modules/cost_centers.py
  modules/projects.py
Labels: size/S

#40 fix: cost center disable, category mapping creation
  modules/categories.py
  modules/cost_centers.py
Labels: size/XS

#41 fix: merchant disable
  modules/merchants.py
Labels: size/XS

#43 refactor: update disable items func
  tasks.py
Labels: size/S

#48 feat: Add qbd item support
  tasks.py
Labels: size/XS

#49 fix: QBD naming
  tasks.py
Labels: size/XS
